translate indonesian end_of_game_b9c329a4:
    # mc "End of event for episode [version_now]"
    mc "Akhir event untuk episode [version_now]"

translate indonesian strings:
    old "Написать Игорю СМС."
    new "Kirim SMS ke Igor."
    old "GG: Ну?!"
    new "GG: Jadi?!"
    old "TT: Чувак, деньги у меня."
    new "TT: Bro, uangnya ada padaku."
    old "GG: Шикарно. \nСколько там?"
    new "GG: Mantap. \nAda berapa di sana?"
    old "TT: Дохренища. \n "
    new "TT: Banyak banget."
    old "TT: Я взял только необходимое."
    new "TT: Aku hanya mengambil yang kita butuhkan."
    old "GG: Когда пойдём к Жлобу?\n"
    new "GG: Kapan kita pergi ke Slob?\n"
    old "TT: Сам схожу. \nТы и так хорошо «поработал».\n"
    new "TT: Aku pergi sendiri. \nLo sudah «bekerja» dengan baik.\n"
    old "GG: Что ты имеешь в виду? "
    new "GG: Maksud lo apa? "
    old "TT: Ничего. \nЯ сам схожу к Жлобу. \nНечего нам двоим рисковать."
    new "TT: Tidak ada. \nAku sendiri yang akan menemui Slob. \nTidak perlu kita berdua ambil risiko."
    old "TT: Как только вернусь, напишу.\n\n"
    new "TT: Begitu aku kembali, aku akan mengabari.\n\n"
    old "GG: Окей. Буду ждать."
    new "GG: Oke. Gue tunggu."
