translate indonesian ep3_3_pictures_d5e0939c:
    # mc "Just as I thought. A hidden safe behind the painting."
    mc "Seperti dugaanku. Ada brankas tersembunyi di balik lukisan."

translate indonesian ep3_3_pictures_33fb6e45:
    # mc "Now I need the password to the safe, but I have no idea how to get it. I'll have to ask Igor, he's the brains behind our team of misfits. I'll text him tomorrow morning."
    mc "Sekarang aku butuh kata sandi brankas itu, tapi aku tidak tahu cara mendapatkannya. Aku harus bertanya pada Igor, dialah otak di tim orang payah kami. Aku akan mengirim pesan kepadanya besok pagi."

translate indonesian strings:
    old "GG: Ку, бро!"
    new "GG: Yo, bro!"
    old "TT: И тебе того же."
    new "TT: Yo juga."
    old "GG: Слушай, у меня к тебе крайне важное дело."
    new "GG: Dengar, ada urusan sangat penting yang perlu kubicarakan denganmu."
    old "TT: Ну-ну…"
    new "TT: Oh ya?..."
    old "GG: Кажется, я нашёл способ \nрасплатиться с нашим долгом!\n"
    new "GG: Sepertinya aku menemukan cara \nuntuk melunasi utang kita!\n"
    old "TT: Хочешь завалить Жлоба? :D"
    new "TT: Lo mau menghabisi Slob? :D"
    old "GG: Никакого криминала. Ну… почти никакого."
    new "GG: Tidak ada kriminalitas. Yah... hampir tidak ada."
    old "TT: Чувак, \nэто по-любому какая-то херня. \nНо так уж и быть, я выслушаю.\n"
    new "TT: Bro, \nini pasti ide ngaco. \nTapi baiklah, aku akan mendengarkan.\n"
    old "TT: Приходи днём в парк, пообщаемся лично. \nПока ты прохлаждаешься, \nя вкалываю как Папо Карло.\n\n"
    new "TT: Datanglah ke taman siang nanti, kita bicara langsung. \nSementara lo santai-santai, \naku kerja keras seperti Papa Carlo.\n\n"
    old "GG: Или как «Раб на галерах»."
    new "GG: Atau seperti «budak di kapal dayung»."
    old "TT: Иди нахуй."
    new "TT: Pergi sana."
    old "GG: Ладно, жди. Приду. "
    new "GG: Baiklah, tunggu. Aku datang. "
    old "Теперь мне нужен пароль от сейфа, но я понятия не имею, как его разузнать. Надо спросить у Игоря, он мозг в нашей команде недотёп. Напишу ему завтра с утра."
    new "Sekarang aku butuh kata sandi brankas itu, tapi aku tidak tahu cara mencarinya. Aku harus bertanya pada Igor, dialah otak di tim orang payah kami. Aku akan mengirim pesan kepadanya besok pagi."
