translate indonesian christie_root_31_0_b23e57a5:
    # mc "I should check my phone. Maybe it's something urgent."
    mc "Aku harus memeriksa ponselku. Mungkin ada sesuatu yang mendesak."

translate indonesian strings:
    old "Проверить телефон."
    new "Periksa ponsel."
    old "TT: Ну и где, мать твою, фотка с Кристи?!!!\n"
    new "TT: Mana foto Christie, sialan?!!!\n"
    old "GG: Бля, я забыл……….\n"
    new "GG: Sial, aku lupa……….\n"
    old "TT: Ещё бы! Легко забыть об обещании после того, \nкак твой друг сделал для тебя доброе дело!\n"
    new "TT: Tentu saja! Mudah sekali lupa pada janji setelah \ntemanmu sudah membantumu!\n"
    old "GG: Бро, всё будет. \nТолько не злись.\n"
    new "GG: Bro, nanti kukirim. \nTenang saja.\n"
    old "TT: Я буду злиться столько, \nсколько посчитаю нужным.\n"
    new "TT: Aku akan tetap marah padamu \nselama yang kumau.\n"
    old "TT: И пока ты не вышлешь мне фотку с Кристи, \nты исключён из списка лучших друзей!\n"
    new "TT: Dan sampai kau mengirim foto Christie, \nkau kucoret dari daftar sahabatku!\n"
    old "GG: Но я твой единственный друг, ау…\n"
    new "GG: Tapi aku satu-satunya temanmu, bro...\n"
    old "TT: Тем более!\n"
    new "TT: Justru itu!\n"
    old "TT: Шли фотку и не беси меня!\n"
    new "TT: Kirim saja fotonya sekarang, jangan bikin aku kesal!\n"
    old "GG: Харош бузить. Я всё обязательно вышлю.\n"
    new "GG: Oke, berhenti ribut. Pasti kukirim.\n"
    old "GG: Она же не гуляет \nголой по дому и не устраивает стриптиз показы по вечерам. \n"
    new "GG: Maksudku, dia kan tidak berjalan telanjang \ndi rumah atau melakukan striptease tiap malam. \n"
    old "GG: Подожди ещё немного, окей?\n"
    new "GG: Tunggu sebentar lagi, oke?\n"
    old "TT: …….\n"
    new "TT: ...\n"
    old "TT: Активирую режим «Хатико».\n"
    new "TT: Mode «Hachiko» aktif.\n"
    old "GG: Ыыыыыыыы!\n"
    new "GG: Hahahahaha!\n"
