translate indonesian christie_root_35_1_b23e57a5:
    # mc "I should check my phone. Maybe it's something urgent."
    mc "Aku harus memeriksa ponselku. Mungkin ada sesuatu yang mendesak."

translate indonesian strings:
    old "TT: Глянул фотку."
    new "TT: Aku sudah melihat fotonya."
    old "TT: 12 из 10!!!"
    new "TT: 12 dari 10!!!"
    old "GG: Знаю, бро! \nВедь я это видел собственными глазами.\n"
    new "GG: Aku tahu, bro! \nSoalnya aku melihatnya dengan mataku sendiri.\n"
    old "TT: Ах ты ж сука, \nрешил поиздеваться надо мной?!\n"
    new "TT: Dasar bajingan, \nkau sengaja mengejekku?!\n"
    old "GG: Всего лишь факт.\n"
    new "GG: Cuma fakta.\n"
    old "GG: Как, по твоему, \nя бы сделал эту фотку?"
    new "GG: Menurutmu, \nbagaimana aku bisa mengambil foto ini?"
    old "TT: Пока что я слишком впечатлён красотой богини, \nи твои комментарии тут излишне. \n\n"
    new "TT: Untuk saat ini aku terlalu terpesona oleh kecantikan sang dewi, \njadi komentarmu tidak diperlukan. \n\n"
    old "GG: Ну ладно. Удачного дня.\n"
    new "GG: Baiklah. Semoga harimu menyenangkan.\n"
    old "TT: И тебе не горевать.\n"
    new "TT: Kau juga.\n"
    old "Отправиться на слежку. Лучше всего начать это делать с самого утра, начав с дома Сьюзен."
    new "Pergi mengintai. Sebaiknya mulai sejak pagi hari, dimulai dari rumah Susan."
